### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#1]
_Note: the launch checklist has been made obsolete by a brand new Launch Guide: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md_

Let's keep the general discussions around what needs to be done in order to get the track launched here in this issue. We can open new, actionable issues for any of the TODO items we identify.

**Comment by NobbZ** [comment]
X?

Katrina Owen <notifications@github.com> schrieb am Fr., 30. Juni 2017,
15:48:

**Comment by kytrinyx** [comment]
@NobbZ Where?

**Comment by kytrinyx** [comment]
@NobbZ Found it. Thanks.

**Comment by zenspider** [comment]
@kytrinyx I'm not sure why I'm getting notifications for this project. Github says "You’re receiving notifications [for this issue] because you’re on a team that was mentioned". What team is that? What's the granularity of teams?

**Comment by stkent** [comment]
I'm guessing it's the `Add track maintainers to @exercism/track-maintainers team (any organization owner)` todo list item.

**Comment by kytrinyx** [comment]
Sorry about that, let me make sure that doesn't trigger a notification.

**Comment by zenspider** [comment]
No worries. Just curious.

**Comment by NobbZ** [comment]
Sorry @kytrinyx for beeing short worded yesterday. I was commuting and inside a crowded underground, felt like beeing a pinball... 

Also, notifications get triggered by @-mentioning the team when initially creating the post. Adding it removing a @ mention doesn't send new emails not deletes it old ones. 

To be honest I really like getting notified about new tracks, but perhaps that's a discussion to be held in another repo?

**Comment by kytrinyx** [comment]
@NobbZ I removed the @ in the boilerplate so that it won't trigger new emails for new tracks. I removed the @ in this post, because if people unsubscribe and then the post gets edited I suspect that they'd get resubscribed (I haven't tested that—probably should).

If you want notifications about new tracks, I'd recommend following https://github.com/exercism/request-new-language-track

**Comment by Stargator** [comment]
I think the documentation got addressed this weekend. And correct me if I'm wrong, but there seems to be a icon in use as well.

![image](https://user-images.githubusercontent.com/7527155/29258926-02e97eae-808c-11e7-8d70-50d09ec03b0a.png)
Is that just a placeholder or is that final?

Just wondering since the icon item on the list hadn't gotten checked off.

I'll keep going over the docs I submitted tonight just to see if there's anything rework can be done.

Next weekend, I'm going to go through the Dart Exercisms and see if there are any unimplemented ones that I can handle. I'm still learning Dart (via AngularDart), but I'd love to see this track get going.

**Comment by kytrinyx** [comment]
I think I just forgot to check off the icon. I'll do that now.

>  I'd love to see this track get going.

Me too! Thanks so much for working on this.

We're in the middle of working on a new redesign, which we will show to contributors and maintainers in the next few days. If you keep an eye on the newsletter http://tinyletter.com/exercism you'll be one of the first to know :) That will be an extra inspiration to get the track launched, I think, because the new site is pretty gorgeous.

Here's a list of unimplemented exercises, with links to the canonical data and other implementations: http://exercism.io/languages/dart/todo

**Comment by kytrinyx** [comment]
@Stargator I spent the day writing a launch guide: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

Not sure how much is missing from this, my brain kind of shut down after 10 hours or so of writing!

**Comment by Stargator** [comment]
@kytrinyx Thanks. I'll probably take a look tomorrow. Going to wind down.

**Comment by kytrinyx** [comment]
> By the way, does this change mean, the original post here will need to be updated?

Yeah, I'm going to go ahead and update it to point to the launch guide, and then we can discuss here in this thread what the best next steps are and open new issues for whatever actionable todo items we come up with.

**Comment by Stargator** [comment]
Okay, so I am going to make a list and feel free to update it. I want to list out everything that is needed, make issues for them, and then tie as much of them to a milestone as possible.

I'm thinking of calling the milestone, LaunchPad. Meaning once we reach LaunchPad, we evaluate if there's anything else needed before launch.
* Determine what language/framework specific concept we want to teach the user during the first 10 exercises
* Need 3 more Exercises
* All the exercises should follow some basic practices, like skipping all but the first test by default, #26, #2, #28, #29
* Need all Exercise test files to be typed for preparation for 2.0, See #27 
* Need track maintainers, at least 2.
* Need documentation up-to-date, can be reviewed as we go and before we launch.
* Need Continuous Integration, See #3 
* Whether to use the dart_test.yml configuration file provided by the chose test framework, [test](https://pub.dartlang.org/packages/test) or instruct the user on the use of the command line
* Review the README and ensure the Contributing, Setup, and other necessary info are either there or referenced.

**Comment by kytrinyx** [comment]
This looks like a good plan @Stargator.

A quick note about this one: https://github.com/exercism/dart/issues/31

I think it would be helpful to explain in the intro of the issue that we want to gradually introduce useful concepts in the test framework and tools, and that this issue is about introducing Setup/Teardown as a part of that.

**Comment by Stargator** [comment]
Will do.

**Comment by kytrinyx** [comment]
@Stargator my comment was about #31 not a new issue.

I meant to suggest that you edit issue #31 to include the background for why we've opened it. As it reads, you kind of need to have been here for the earlier discussion to understand what it's about.

I don't think that we should edit `ABOUT.md` to say anything about gradually introducing tools.

`ABOUT.md` is introductory copy for the track landing page. You can read more about this here: https://github.com/exercism/docs/blob/master/language-tracks/documentation/introductory-copy.md

I think #33 should be closed.

**Comment by Stargator** [comment]
Okay, sorry about that. Closed #33 and will update #31

**Comment by Stargator** [comment]
@kytrinyx How's #31 look now?

**Comment by kytrinyx** [comment]
That looks great! There's a sentence I don't understand:

> A lot of this is already done, but problems written in Dart and asking for a solution.

**Comment by Stargator** [comment]
Addressed

**Comment by kytrinyx** [comment]
Ah! Obvious in retrospect :) thanks!

**Comment by Stargator** [comment]
Just added a new exercise thanks to @fwip for reviewing. Additionally, current exercises are ordered and labeled as core.

**Comment by Stargator** [comment]
@kytrinyx We are making some great progress thanks to @fwip and @kabiir. Once their exercises are added and #31 is completed, I think it would be a good time to review the track and look for anything outstanding.

I haven't seen @SuperPaintman. But he was active on Github in August, not Sept. Hopefully he's okay.

That's the only thing I can think of is meeting the 2 maintainers requirement.

You can review [the checklist I made here](https://github.com/exercism/dart/issues/1#issuecomment-327029612)

**Comment by kytrinyx** [comment]
@Stargator Congrats, you've all been kicking butt and taking names! 💥 

I've emailed you a quick question about maintainers, but honestly it's not a hard requirement. There are a bunch of tracks on Exercism (unfortunately) that have lone maintainers. We're trying to fix it, but we're not there yet.

**Comment by kytrinyx** [comment]
> I think the new site may help with that cause of the increase interaction within the community it promotes.

Agreed. It's going to be a lot better, I think.

**Comment by Stargator** [comment]
@kytrinyx @kabiir @fwip 

We have completed everything in [milestone LaunchPad](https://github.com/exercism/dart/milestone/1).

I [created a list](https://github.com/exercism/dart/issues/1#issuecomment-327029612) and there's just two items left:

> Determine whether to use the dart_test.yml configuration file provided by the chosen test framework, test or instruct the user on the use of the command line
> Review the README and ensure the Contributing, Setup, and other necessary info are either there or referenced.

Really, I only think we need to worry about the documentation is good for contributors. There would have to be a dart_test.yml file for each exercise and I don't think it will give us any real benefit as the user will still need to run the tests via command line.

**Comment by kabiir** [comment]
@Stargator I think I can address the problem for 'dart_test.yml' I'll be making a PR soon. There needs to be only 1 'dart_test.yml' and it'll be in the root directory. And if we use this then we won't need the current exercise test script which loops through all directories and executes those tests. Honestly I wasn't a fan of the current implementation, but didn't know  if there was a more elegant approach. It's an idea I have, I'll test it on my local machine and if it works ill send a PR

**Comment by Stargator** [comment]
I meant to have the dart_test.yaml to help users that tackle the exercises. I don't think the test configuration would allow us to change the files like exercises_test.dart does.

Cause by default the test suites for the exercises don't reference the example.dart solution for each exercise. So there's going to be some kind of manipulation, but that stems from Exercism's needs.

But if there is an alternative, feel free to submit it or open an issue and we can hash it out.

**Comment by kytrinyx** [comment]
> We have completed everything in milestone LaunchPad!! 🎉 🎉

Exciting! As soon as you're ready, flip `active` to true in the `config.json` and the track will go live in the next deployment. (I try to deploy at least once a day).

**Comment by Stargator** [comment]
Okay, so it's up to the maintainers to decide if we are ready? Okay.

In that case, I'm going to through the documentation (README, docs/, and CONTRIBUTING). And look for anything to touch up.

**Comment by kytrinyx** [comment]
> Okay, so it's up to the maintainers to decide if we are ready?

Yepp—you all know your track.
