### ISSUE TITLE
travis.yml: Remove presubmit from config and ensure builds fail when tests fail.

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#120]
During the Scrabble Score Pull Request, it was revealed that the Travis builds were passing even when files needed to be formatted. Additionally, the presubmit script was being executed, but that only needs to happen before submitting a PR, not when a PR is being built.

Additionally, when tests either fail or time out the Travis Build still passes when it should fail.

**Comment by jvarness** [comment]
`dartfmt` has an option to do a dry run and set the exit code to 1 if there are changes. That might be a good option.

**Comment by Stargator** [comment]
@jvarness We ran it via the check_formatting scripting, so it runs on all platforms.

**Comment by jvarness** [comment]
@Stargator if your environment has the dart sdk installed though, won't it have `dartfmt` installed by default? Are there installations that don't include `dartfmt`?

**Comment by Stargator** [comment]
@jvarness You are right, the script allows checks the formatting of the config.json. So instead of a single line for each command we rolled similar commands together in the check_formatting.dart and the presubmit.dart scripts.

**Comment by Stargator** [comment]
> @Stargator if your environment has the dart sdk installed though, won't it have dartfmt installed by default? Are there installations that don't include dartfmt?

An additional point to make is that the SDK has a set version of the dartfmt package (dart_style). So if you want a newer version you'd have to run `pub global activate dart_style`. So if we add that to the script, then it would more justify manually running the dartfmt executable since it would follow updating the global package version.

**Comment by jvarness** [comment]
@Stargator I've been working on this but I've hit some snags.

Looks like the Dart runner for Travis doesn't honor when exit codes are set within a Dart script. I'll need to investigate a little more and get back to you.

I figured out how to make formatting fail and how to run all the tests, but there's weird stuff happening with setting exit codes.

**Comment by Stargator** [comment]
I've experienced this with Jenkins. I resolved it by throwing an error when the exit code was non-zero.

**Comment by jvarness** [comment]
Throwing the error is fine, but after rebasing with master, it looks like the jobs are now stalling when the formatting of all the files is checked:

https://travis-ci.org/jvarness/dart

**Comment by Stargator** [comment]
Resolved in #129
