### ISSUE TITLE
Preparing for Dart 2

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#123]
@exercism/dart So Dart 2.0 is expected to release sometime this summer, with it comes a lot of changes to the API which impacts a few exercises and some of our scripts (as noted in the [dart-2](https://github.com/exercism/dart/compare/dart-2) branch.

The exercises affected are:
* anagram
* difference of squares
* gigasecond (due to a change in the API)

In their current state, this means these exercises can only support Dart 1 or Dart 2. Whereas the remaining exercises are compatible with Dart 1 and Dart 2.

With some changes, I think anagram and difference of squares could be considered compatible with both 1 & 2.

Gigasecond's use of the DateTime API means we will have to replace the Enums used with actual int values.  But otherwise, our current exercises should be good.

The repository on the other hand requires updates to create_exercise and exercise_test in order for them to run in Dart 2.0. Changing the repo to use the Dart 2 SDK, shouldn't impact users implemenation of the tests.

Having said all of that, these are my proposed changes:
- [x] Apply minor fixes to anagram, difference of squares, and gigasecond to make them Dart 2.0 compatible as well as Dart 1.0 compatible. 
- [x] Set the SDK limitations for all the exercises's to be between Dart 1.24.0 and Dart 2.0.1.
- [x] Set the SDK constraint for the repo's pubspec.yaml to be at or above Dart 2.0.0 and below Dart 2.1.0 to avoid any API changes after 2.0's release.
- [x] Update the create-exercise script to include sdk constraints for new exercises
- [x] Use [dart2_constant](https://github.com/dart-lang/dart2_constant) as a polyfill to handle the transition between Dart 1 and Dart 2. The names of many constants were changed to fit a new naming convention, this library will resolve that.

**Comment by jvarness** [comment]
Are people able to remain compliant on 1.24.0 if they use strong mode (adding `-c` to the command line) or are there even more non-passive changes between 1.24.0 and 2.0?

**Comment by Stargator** [comment]
There are more non-passive changes, like how you build an application.

On the whole, the Dart API deprecates what has been replaced or removed, but it's still accessible. At least in the dev versions of the SDK. Will those deprecated classes remain at release? I don't know. 

Some Dart API the classes have been renamed to lower_snake_case and most of those are in the scripts at the root of our project.

For example, in the dart:convert library JSON is would be json and in the DateTme object, the constants for months(APRIL, MAY, etc.) are now lower case as well (april, may, etc). And some previous classes/methods were removed or replaced with an alternative.

So most of the exercises as of branch [dart-2](https://github.com/exercism/dart/tree/dart-2) are compliant with Dart 1.24.2 and Dart 2.0

**Comment by Stargator** [comment]
Closed with #134
