### ISSUE TITLE
Convert bash script fetch-configlet to Dart

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#136]
While I think this script can currently be used on all platforms, since it seems to be written well enough, this is the **Dart** track and I think it may be a good idea to have it written in Dart.

This may mean turning it into a utility class that is stored in lib/src/ and imported by create_exercise and other scripts that would need to ensure the user has configlet or the latest version of configlet.

Or the script could stay in the bin/ but just written in Dart.

**Comment by devkabiir** [comment]
Also, the current one doesn't work on windows. I have to manually install/update. Or have weird configs of bash on windows. Provided we do have bash on windows now. But it's far from usable IMO.

**Comment by kytrinyx** [comment]
I've opened https://github.com/exercism/dart/pull/407 which updates to the latest version of the fetch-configlet script(s). These work on all the platforms.

I would prefer to not port exercism-wide tooling to individual languages, as it increases the amount of work necessary to maintain a track.

Given the above, would you be okay with closing this issue?

**Comment by devkabiir** [comment]
@kytrinyx Thanks for the update, I'd choose consistency with other tracks here. Closing this in favor of #407
