### ISSUE TITLE
Fix getting started instructions for dart

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/dart#143]
Some exercise README templates contain links to pages which no longer exist in v2 Exercism.

For example, C++'s README template had a link to /languages/cpp for instructions on running tests. The correct URLs to use can be found in the 'Still stuck?' sidebar of exercise pages on the live site. You'll need to join the track and go to the first exercise to see them.

Please update any broken links in the 'config/exercise_readme.go.tmpl' file, and run 'configlet generate .' to generate new exercise READMEs with the fixes.

Instructions for generating READMEs with configlet can be found at:
https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generating-a-readme

Instructions for installing configlet can be found at:
https://github.com/exercism/docs/blob/bc29a1884da6c401de6f3f211d03aabe53894318/language-tracks/launch/first-exercise.md#the-configlet-tool

Tracking exercism/exercism.io#4102

**Comment by Stargator** [comment]
@jackhughesweb How did you determine which links were broken. So far all the links take me to a website. Though one website is a blank page. I'd like to specifically find the ones that were 'broken".

**Comment by jackhughesweb** [comment]
@Stargator Sorry for any confusion - this was an automatically created issue to keep track of which languages have/haven’t been checked yet. We found some README templates had internal links which were broken in v2 of the website, however this doesn’t apply to all languages - please close this issue if everything is ok 😊

**Comment by jackhughesweb** [comment]
I’ve just checked the template file for Dart - it does seem to have a broken link (to exercism.io/languages/dart) (I’m on mobile now, but will fix the link later unless someone sends a PR first).
