### ISSUE TITLE
Recommended next exercises to implement

### ISSUE THREAD

**Issue by jvarness** [exercism/dart#149]
**Disclaimer**: The maintainers' current priority is working on getting this track ready for v3. As such, instead of working on new exercises, we recommend you check out [Dart issues on the v3 repo](https://github.com/exercism/v3/issues?q=is%3Aopen+is%3Aissue+label%3Atrack%2Fdart)

In Slack, Stargator gave us a list of recommended exercises to implement next. It includes the following:

- [ ] bowling
- [ ] book-store
- [x] bracket-push (@johnngugi)
- [x] change (@jvarness)
- [ ] circular-buffer
- [ ] crypto-square
- [ ] custom-set
- [X] darts (@amscotti)
- [x] diamond (@jvarness)
- [ ] flatten-array
- [ ] go-counting
- [ ] grep
- [x] isogram (@jvarness)
- [ ] list-ops
- [x] luhn (@amscotti)
- [ ] markdown
- [ ] matrix
- [ ] ocr-numbers
- [x] pangram (@amscotti)
- [x] pascals-triangle (@jvarness)
- [x] rest-api (@Stargator)
- [x] robot-simulator (@Corentin-Leffy)
- [ ] say
- [ ] tournament
- [ ] wordy

**Instructions:** if you want to start working on one of these exercises, edit this post, put a check mark on it, and put your name as well. If you don't have permissions to edit this post, tag me and I'll edit it for you.

Please follow the [contribution guidelines](https://github.com/exercism/dart/blob/master/CONTRIBUTING.md) when submitting pull requests.

**Comment by Stargator** [comment]
Thanks for posting the list, @jvarness.

To be clear this was just my perspective and I am just a mere mortal.

If there's a problem specification that interests you and it's not listed, feel free to implement it.

**Comment by jvarness** [comment]
Think nothing of it @Stargator, these are fun 😄 if I see a different exercise I want to implement I will.

**Comment by johnngugi** [comment]
@jvarness I would like to implement bracket-push

**Comment by Stargator** [comment]
@jvarness @devkabiir Are there any exercises remaining, or that we implemented from the list, that you think would make for good core exercises?

To me a core exercise should:
A) Build off of the previous core exercises
B) Either solve a problem by 1) using the same mechanism as before but in a new way or 2) presenting a new kind of problem.

For example devkabiir's work on Minesweeper and Binary Search Tree, these are new kinds of problems but may contain previous lessons from core exercises.

All of our core exercises should be building towards getting students ready for those kinds of problems which are complex and involve multiple types of problems to solve a big problem.

**Comment by jvarness** [comment]
@Stargator these are good questions. I think we might want to create a new issue to discuss this and divide the work between us to figure out which exercises we think are good exercises for the core path.

**Comment by Stargator** [comment]
Just adding a note @jvarness left in a PR:

> It would be interesting to see if this could return a Stream of the sequence. One of Dart's unique features is the amazing support for asynchronous computing, yet I can't recall any of our exercises supporting async processing.

So if possible do consider how to leverage Dart features into the test cases for an exercise. That way it would force the students to utilize that feature or look up how to leverage it.

**Comment by Corentin-Leffy** [comment]
Hi there ! 
Is it possible to take the robot-simulator exercise please ?

**Comment by Stargator** [comment]
@Corentin-Leffy, sure. Consider it yours.

**Comment by Stargator** [comment]
Closing this issue since we are moving to v3. New Exercises should be implemented for the Concept Exercises. See https://github.com/exercism/v3 for more info.

See the V3 Dashboard for the Dart Track to see where you can help: https://tracks.exercism.io/dart/v3/launch
