### ISSUE TITLE
Dart 2.0 Builds will fail when formatting is wrong, but still run tests

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#156]
As shown in this [build](https://travis-ci.org/exercism/dart/jobs/477937570), the Dart 2.0 based builds will still fail when there's a formatting issue, but they still run the tests.

That doesn't cost Exercism any money, but it does eat up resources and slows down whatever Exercism project has a build waiting to execute.

**Comment by devkabiir** [comment]
Relevant travis-ci/travis-ci#1066 issue and possible solution [issuecomment-425757599](https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-425757599)

**Comment by devkabiir** [comment]
Also, how about using [mono_repo](https://github.com/dart-lang/mono_repo), it seems to fail fast for any failures in my https://github.com/devkabiir/decorator and https://github.com/devkabiir/built_json_schema repos

**Comment by Stargator** [comment]
OBE, this is no longer an issue. May have been on Travis CI's side
