### ISSUE TITLE
Dart 2.0+ Migration

### ISSUE THREAD

**Issue by devkabiir** [exercism/dart#157]
Its been almost 6 months since dart 2.0 stable was release. I think we should raise the sdk constraint for the repo and all exercises to `>=2.0.0` perhaps even `>=2.1.0`. The exercises do pass against Dart 2.0 so the changes to them should be minimal.

Thoughts? @Stargator  @jvarness.

**Comment by jvarness** [comment]
I'm open to doing this. Especially with Dart maturing as much as it is, if someone is wanting to learn more about Dart best practices, much of the Dart 1.X best practices are sort of defunct with the release of 2.X.

**Comment by devkabiir** [comment]
We should also `mono_repo` package for auto generating manageable travis config with granular control over each exercise. This also allows for a gradual migration of each exercise to dart `>=2.0`

**Comment by jvarness** [comment]
`mono_repo`ing doesn't sound like a bad idea, but how would that work with presubmit? The parent project that is the dart track would have to use 1.X or 2.X exclusively right?

Perhaps if Travis can be smart enough to detect changes within the `exercises` tree structure and only run tests for things that were changed that could work!

**Comment by devkabiir** [comment]
> 
> 
> `mono_repo`ing doesn't sound like a bad idea, but how would that work with presubmit? The parent project that is the dart track would have to use 1.X or 2.X exclusively right?

Somewhat Correct! But we can specify dart version for each exercise, Since under the hood each of them will run in a different Travis job (parallel). The parent repo doesn't necessarily need both 1.x and 2.x. (currently it does because it has scripts that try to work in both versions). 

If we go the mono_repo way, there will be following jobs

1. 1 Job for linting config.json/exercism track specific linting
2. N jobs for N exercises, each of which runs lint/format/test  (3 tasks)
    - We could further split or mix-and-match to increase parallelism or decrease no. of jobs
       depending on how jobs are allotted to the exercism organization. If we are running too many jobs for each git push we can combine them or if it's better to run more jobs then we split every action/script into a job (faster build times). We don't have slow build times per say.

But yes! we can do really crazy configs. We just need to discuss how the pipeline should work.

Also this can allow to fail fast and only test changed exercises #63 (haven't looked much in this but I'm pretty sure it's possible).

**Comment by Stargator** [comment]
@devkabiir @jvarness Some of the work done to ensure the Dart repo scripts and the exercises work in both 2.0 and 1.0 made headway towards this. I didn't want to cause an abrupt change for users.

Sometimes migration to a new version can take weeks to months for individuals tied to projects that may use Dart.

So I don't think 2.0 and 1.0 are too far apart where we can't support both for now.

I do have a branch in the works to address some lingering migration issues.

However, I do feel open to migrating the Dart repo scripts (create_exercise.dart, check_formatting.dart, presubmit.dart, etc) to 2.0 only.

**Comment by Stargator** [comment]
@devkabiir I just realized the idea to use `mono_repo` would require adding a `mono_pkg.yaml` file to eahc of the exercise directories. So unless we can avoid including those files when the user downloads the exercise, then I would not be interesting in using `mono_repo`

**Comment by devkabiir** [comment]
`mono_repo` just uses those configs to automatically create jobs in travis.ymal config. In my draft #161 we aren't using mono_repo because I realized we can accomplish the same using our create_exercise script

Now if we migrate the `exercism_dart` package to dart 2.0 only, then as demonstrated in #161 we can set the `Repo` jobs to run in a dart 2.0 environment and run `Exercise` jobs in `1.24 && 2.0 && dev` environments. I need some time to confirm this works as I think it does. After that we can decouple environmental dependencies between the `exercism_dart` package and `__exercise_name__` packages
