### ISSUE TITLE
Install dart link change suggestion

### ISSUE THREAD

**Issue by rickygutim** [exercism/dart#162]
Hi!

I suggest that the link for the automatic installation of dart on INSTALLATION.md should change from https://www.dartlang.org/install to https://www.dartlang.org/tools/sdk or to include the second link as an option too. 

I recently started the dart track. I already had flutter installed on my computer, so I thought everything would worked fine but I couldn't use pub. So I went to the install dart section and followed the steps which took me to this page https://www.dartlang.org/install that suggests to install flutter, web or server. But I already had flutter installed, which wasn't enough for the dart track, and I didn't wanted to installed web or server. The right solution for me was to install the dark sdk at https://www.dartlang.org/tools/sdk.

That's why I think the link to install the dart sdk should replace the install dart link or should be added as an alternative solution.

Cheers :)
Ricky

**Comment by Stargator** [comment]
@rickygutim Good point, I'll update it soon
