### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#196]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by Stargator** [comment]
@kytrinyx It's been awhile since we had the discussion about stubs, but I don't see any documentation specifying what is suppose to be in the stub files or how they align with the layout of a file-based track.

**Comment by kytrinyx** [comment]
Yeah, what goes into it will depend on the track. For some tracks it is literally an empty file (named the right thing based on what the test is expecting, and having the right extension).

For others they might need to include parts of the standard library that aren't included in the core language (Ruby has that, PHP as well in some places). Or there might be header files with includes or macros.

The basic thing is that we don't want to "give away" the answer to the exercise, for example it's probably generally important for them to define the API of the code themselves (if the tests don't specify the API already), but that we don't want to make them google around to figure out things that might be really hard to google for when you don't know the language.

So essentially: we're leaving the key decisions up to maintainers, but the main idea is reduce friction without removing the learning-opportunity that the _exercise itself_ represents.

**Comment by Stargator** [comment]
@exercism/dart  After considering this for awhile, I believe we have stubs for all of our exercises. Unless there are any objections I will close this.
