### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#2]
- Is there a style guide for Dart?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- When you add a linter, edit the pull request template [link]
- Update the pull request template with checks that are appropriate for this track
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by Stargator** [comment]
> Is there a style guide for Dart?
 [Yes](https://www.dartlang.org/guides/language/effective-dart)

> Are these styles encouraged or enforced?
  Encouraged, but can be enforced by configuring the [analysis_options.yaml](https://www.dartlang.org/guides/language/analysis-options) and/or using [the dartfmt tool](https://github.com/dart-lang/dart_style#readme)

> Are there any conventions that we should adopt on this track for the sake of consistency?
> Can we enforce these?
  The conventions are mentioned about in the link for the style guide. There are definitely some we may **want** to enforce** but few **I** think we should.

> Is there a linter? Are there many? Should we use one?
The analysis_options.yaml file configures the analyzer which is essentially a static analyzer for the given project. We can look at the linting as well as general rules to avoid errors.

> When you add a linter, edit the pull request template [link]
 The linter comes packaged with the Dart SDK. If you have Dart installed you have access to the analyzer.

> Is there a common convention for filenames? If not, what should our convention be
[Filesnames generally follow the convention of **lowercase_with_underscores**](https://www.dartlang.org/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)

**Comment by kytrinyx** [comment]
Thanks. It sounds like the reasonable thing to do for the Dart track is to

- link to the style guide and ask people to respect it
- start off by not enforcing anything
- document the convention for filenames in the README of this repository

If at some point we realize that we are seeing some annoying inconsistencies, we can open an issue to discuss whether or not it's worth enforcing consistency for that particular thing.

**Comment by Stargator** [comment]
As far as not enforcing anything that may depend on decisions related to #24

**Comment by Stargator** [comment]
#28 Created to ensure some exercises follow a desired standard of skipping all but the first test.

Are there any current issues with consistency between exercises?

**Comment by kytrinyx** [comment]
> Are there any current issues with consistency between exercises?

Not that I know of. I think we can close this one and work off of the newly opened issues.

**Comment by Stargator** [comment]
Agreed.
