### ISSUE TITLE
Tests page has numbering that isn't consistent

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#22]
The [tests page](http://exercism.io/languages/dart/tests) has numbered bullet points that somehow get reset.

I don't see that when viewing the markdown file in Github, so I am not sure what the process is that interprets the file.

This is also affecting [the Java track's test page](http://exercism.io/languages/java/tests)

Adding an image just for future reference of the original problem:

![redcarpet01](https://user-images.githubusercontent.com/7527155/29997282-646f9e96-8fdd-11e7-8d04-5ba2e92ac448.png)

**Comment by iHiD** [comment]
The markdown parsing code we're using has changed for v2, so whatever turns up here will need to be applied there too.

**Comment by Stargator** [comment]
@iHiD I actually do not see the Tests page for Java in v2. Are you saying there are two different parsing logic for v2 and v1?

Since v2 of Java isn't using the TESTS.md page it's hard to tell if v2 handles v1 the same from where I am.

**Comment by kytrinyx** [comment]
I'm pretty sure that if we fix the markdown for v1 it will also be fixed for v2 (but yes, v2 does markdown parsing differently—better—than v1).

**Comment by Stargator** [comment]
@iHiD @kytrinyx Should this issue be closed and opened in a different repo? Since it seems to concern the markdown parsing, I want to check if this is okay.

**Comment by Stargator** [comment]
[Comment from NobbZ](https://gitter.im/exercism/dev?at=59aadd0bba0f0f6e380d4bcc):

> Also I can confirm, that v2 suffers from the same problem, I posted the dart test-documentation straight into a comment on my own exercises ;)

**Comment by kytrinyx** [comment]
@Stargator Yeah, would you mind posting reproduction steps in https://github.com/exercism/v2-feedback/issues ? (A markdown comment that exhibits the same behavior as the dart test docs would probably be our best bet here)

**Comment by Stargator** [comment]
@kytrinyx I will post the same thing there as well and close this issue.

My findings:

Redcarpet with code formatting as seen in the image in the initial post does not convert to the expected html format. The code formatting breaks the numbering for lists.

I created a jekyll project to test our Markdown library redcarpet. You can find it [a project for redcarpet here](https://github.com/Stargator/markdown-with-redcarpet/tree/red-quotes) and [a jekyll project using kramdown here](https://github.com/Stargator/markdown-with-kramdown).

I will be making the same post in the redcarpet project as well by COB today.

The problem remains when using quotes with redcarpet:
![redcarpet-quotes](https://user-images.githubusercontent.com/7527155/29997577-bf8820d0-8fe4-11e7-975c-a43dc1cc3543.png)


Or **not** using any formatting at all:
![red-no-formatting](https://user-images.githubusercontent.com/7527155/29997600-39cb0b78-8fe5-11e7-92ed-adcdd645e779.png)


Comparatively, Kramdown does *not* have this issue:
![kramdown-mark](https://user-images.githubusercontent.com/7527155/29997603-55df4612-8fe5-11e7-899f-277bb1837f2a.png)

Though I do not know the full scope of our use of redcarpet, so I do not know if there is anything specific that redcarpet does that we depend on.

As stated, this will be posted in the aformentioned repo by @kytrinyx  as well as the redcarpet repo.

**Comment by kytrinyx** [comment]
This is some great troubleshooting, @Stargator. Thank you.
