### ISSUE TITLE
Dart 2.0 will remove optional typing from language

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#24]
As the Dart team announced Dart 2.0, they did so by speaking about [making Dart a typing system and removing the optional typing in phases](http://news.dartlang.org/2017/06/a-stronger-dart-for-everyone.html).

This month, they encouraged folks to get their code [ready for Dart 2.0 by enabling strong mode and utilizing the dartdevc compiler](http://news.dartlang.org/2017/08/getting-your-apps-ready-for-dart-20.html).

For exercism, this means code written in Dart 1.0 to pass our tests, may not work for Dart 2.0.

On the plus side, we have not officially supported the Dart exercise. So we can opt to make the code written use the dartdec compiler and enable strong mode by updating the pubspec.yaml file and adding an analysis_options.yaml file, respectively.

However, users may still try to write the code with optional typing. So maybe each exercise's README can be updated to highlight these requirements.

We could also include it somewhere in the docs.

Thoughts? @kytrinyx @iHiD @SuperPaintman

**Comment by Stargator** [comment]
I should note, there is no specific or general release date given by the Dart team. So my guess is it could be this year or next year.

**Comment by kytrinyx** [comment]
I would suggest that we wait until we know more about their timeline.

We can update the onboarding instructions to make people aware of the difference, and make sure that we update our exercises to support the new syntax in time for the Dart 2.0 release.

**Comment by Stargator** [comment]
@kytrinyx I understand wanting to know more about their timeline. But from my review of [their news page](http://news.dartlang.org/), they don't announce anything until it is already available.

[Announced and released Dart 1.24 in June on the same day](http://news.dartlang.org/2017/06/dart-124-faster-edit-refresh-cycle-on.html)
[Announced and released AngularDart 3.0 in May on the same day](http://news.dartlang.org/2017/05/angulardart-3.0-easy-upgrade-better-performance.html)
[Dart 1.23 in April](http://news.dartlang.org/2017/04/dart-123-better-strong-mode-support.html)
[Dart 1.22 in February](http://news.dartlang.org/2017/02/dart-122-faster-tools-assert-messages.html)
[Dart 1.21 in December 2016](http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html)
[AngularDart 2.1 in November 2016](http://news.dartlang.org/2016/11/angulardart-21-and-new-components.html), which makes a point to say they announced/launched AngularDart 2.0 at a summit event. Which gives me the impression we won't have any other heads up about Dart 2.0 until it's already out.

Last year, when they talked about Dart's future for 2017 and "beyond", [they left out specifics](http://news.dartlang.org/2016/10/dart-in-2017-and-beyond.html). So they only will talk about something when they feel either it's ready or close to done.

Hence why given the fact they announced Dart 2.0 in June and then encouraged folks to get their ready for Dart 2.0 in August makes me feel it's closer to release, assuming nothing critical prevents thier progress.

I know this is painting the picture its closer than I originally guessed, but I wanted to look over their habit of public announcements when compared to releases and they are much closer than I thought.

At the very least, we can update our tests to be typed and that _may_ encourage some behaviors from our users that will help with the migration.

**Comment by kytrinyx** [comment]
> Which gives me the impression we won't have any other heads up about Dart 2.0 until it's already out.

That's totally fair.

> At the very least, we can update our tests to be typed and that may encourage some behaviors from our users that will help with the migration.

Just so I'm sure I understand: we can update the tests to be typed and it would work for both v1 and v2?

**Comment by Stargator** [comment]
Yes, since in v1 typing is optional. It would be different if v1 had no typing and v2 had typing,

But it's optional, so our tests can be updated.

**Comment by kytrinyx** [comment]
Ah, ok, that makes more sense now, thanks for clarifying.

I think updating now seems like the best plan, then.

We could use this as a basis for opening a number of "good first patch" issues https://github.com/exercism/docs/blob/master/language-tracks/launch/open-issues.md

**Comment by Stargator** [comment]
Sounds good!

**Comment by Stargator** [comment]
I'll make the Hello World exercise the template and reference that in the tickets.

**Comment by Stargator** [comment]
Closing as issue #27 will take over from here.
