### ISSUE TITLE
Documentation: Adding further information about tests (e.g. skipping)

### ISSUE THREAD

**Issue by bryophyta** [exercism/dart#246]
I have not been able to locate much information in the documentation for the Dart track about how testing a solution works, in particular about the default settings of skipping most tests, and how to change this setting.

It may be that I've overlooked something in the docs, but I only managed to understand how test skipping works by looking at the documentation for other tracks, and then looking through the exercise_name_test.dart files to see how it is implemented in the Dart track.

In the instructions for an exercise on the JavaScript track, it says the following:

> In the test suites all tests but the first have been skipped.
> Once you get a test passing, you can enable the next one by changing xtest to test.

I was thinking it could be useful for the Dart track instructions to include something like:

> In the test suites all tests but the first are skipped, by default.
> To enable any additional tests, change "skip: true" to "skip: false" in the /test/exercise_name_test.dart file for the exercise.

It might also be helpful to include a brief explanation of the rationale for only enabling one new test at a time. And perhaps of how to interpret the readout (i.e. the meaning of the +, -, and ~).

I'm a bit new to this (my first issue contribution), so I hope I'm going about it the right way. My apologies if this information can be found in the docs somewhere, but as I mentioned I wasn't able to find it in my search. I've also looked through the 'similar issues' and wasn't able to find anything about tests in terms of the documentation, as opposed to the implementation.

I'd be happy to make a pull request if folks think it would be good to include something like the above instructions in the documentation.

**Comment by Ylarhc** [comment]
Totally agree with that, I've seen many people submitting their solutions being wrong thinking it was correct because it "passed" tests.

**Comment by Stargator** [comment]
Closing due to @Corentin-Leffy's work on #265
