### ISSUE TITLE
Improve the method to test the programs through CLI.

### ISSUE THREAD

**Issue by faizanmohiuddin482** [exercism/dart#247]
unable to run/test any program.

**Comment by Stargator** [comment]
@faizanmohiuddin482 I'm going to need more information here.  The title references the CLI, do you mean `pub` or Exercism's CLI?

What steps are you taking to run the program or execute the tests?

**Comment by Stargator** [comment]
@faizanmohiuddin482 Would happen to be using Dart's 2.8.0-dev version? We have an issue (#249) where we note it is causing some failures in the tests.

**Comment by Stargator** [comment]
@faizanmohiuddin482 closing this until more information is given. Feel free to reopen it once you are ready to provide more details.
