### ISSUE TITLE
hello-world problem failed to precompile test

### ISSUE THREAD

**Issue by HtetLynnHtun** [exercism/dart#254]
When I run ```pub run  test```, this happened.
```
/flutter/.pub-cache/hosted/pub.dartlang.org/test_core-0.3.9/lib/test_core.dart:69:5: Error: 'unawaited' is imported from both 'package:meta/meta.dart' and 'package:test_api/src/utils.dart'.
    unawaited(Future.error('Dummy exception to set exit code.'));
```

**Comment by Stargator** [comment]
Ah.., you may not be able to use the Flutter's version of Dart to run the tests. Do you have Dart installed separately from Flutter?

**Comment by devkabiir** [comment]
Closing. Please feel free to comment/open another issue if the problem persists.
