### ISSUE TITLE
Update test runner to use the new path for example implementation

### ISSUE THREAD

**Issue by devkabiir** [exercism/dart#299]
Per https://github.com/exercism/dart/pull/298, example implementations are moved from `lib/example.dart` to `.meta/lib/example.dart`. This breaks the existing test runner.

Relevant:
 - https://github.com/exercism/dart/blob/8ec254ff2c33c98850b5e35e95a63c81fb1a5bd3/test/exercises_test.dart#L69.

**Comment by iHiD** [comment]
@devkabiir Is this as simple as changing the line you specified (and the one a few lines down), or is there something more complex that needs doing?

**Comment by devkabiir** [comment]
Yes it should work see #300.

But there's also #296 blocking the `Test` workflow from running altogether. To unblock `Test`, relevant lines that need to be removed are https://github.com/exercism/dart/blob/main/bin/check_formatting.dart#L8-L17

And finally the following line might need updating as well, since I don't know if the latest version of `configlet` supports the `configlet fmt .` command.
https://github.com/exercism/dart/blob/c871761da1d96fcef9570f61374dfe1bdf432a5b/bin/presubmit.dart#L9

These are quite simple changes, but I can't approve my own PR.

**Comment by iHiD** [comment]
If you tag @exercism/maintainers-admin into any PRs, Erik will approve them for you :)
