### ISSUE TITLE
Activating sound null safety breaks test code

### ISSUE THREAD

**Issue by ArnaudCalmettes** [exercism/dart#314]
Hi there,

I have very recently started practicing on the Dart track. As I'm willing to take the habit of working with best practices in place, I've been activating sound null safety on all the exercises I've done, and it's been working seemlessly so far.

However, on the "Binary Search Tree" exercise, it seems to conflict with the test code because the tests are navigating the BST without checking that the nodes aren't `null`.

I'm not quite sure how this problem should be addressed. I am well aware that sound null safety and the `?.` syntax came out with the most recent version of Dart and this is no small change, but at the same time it seems to me that their use is a good practice that people learning Dart should be encouraged to adopt early.

What is your policy about this feature ? Any plans to upgrade the exercise codebase to activate and encourage it by default ?

**Comment by devkabiir** [comment]
We recently did migrate our practice exercises to NNDB. And the latest version of BST tests navigate the BST nodes by asserting they are not null using the `!` suffix. It is also possible to write tests to check every node individually for null values, however that will be too verbose and the `!` achieves the same effect, that is, fail the test if the BST is not in a certain state. 

The latest version of BST might not be live on exercism yet, as exercism is in the process of moving to v3. If you like, you can checkout the latest code from this repo and practice each exercise in NNDB. The practice exercises are available at `exercises/practice/<exercise-slug>`.
