### ISSUE TITLE
Create a script to be used by Travis for testing exercises against reference solution

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#34]
Stemming out of the conversation at #3.

We need a script that Travis can execute, along with the current scripts/commands, that will do the following:
* Copy the exercises directory to a temp directory.
* Go into each exercise and modify the test suite's import path.
   * The modification will be replacing the normal import for "bob.dart", for example, to "example.dart". The example.dart file in each exercise acts as our reference solution. The answer key to the problems in the exercise.
* Run `pub run test` on each exercise.

**Comment by Stargator** [comment]
Additionally, you can look at the [Track config file](https://github.com/exercism/docs/blob/master/language-tracks/configuration/track.md) to see what the reference solution and test file patterns are.

The Track's config file can be [found here](https://github.com/exercism/dart/blob/master/config.json)

**Comment by kytrinyx** [comment]
It would also need to change the test suite so that none of the tests are skipped.

**Comment by Stargator** [comment]
@kytrinyx It seems the mighty @SuperPaintman has already thought about this. The test file in the root test directory already looks at the command and replaces the use of the normal file with the reference solution and then runs all the tests (no skipping).

You can see this by running `pub run test` from the root directory of our project. You'll see all the tests are run and they are successful. I just need to add that step to Travis and we'll be set.

I'm also going to check that the right exercise is properly labeled before showing the test results.

**Comment by kytrinyx** [comment]
> It seems the mighty @SuperPaintman has already thought about this

This is great news! Alright, it looks like we're in great shape for CI, then.

**Comment by Stargator** [comment]
Closing since this was implemented.
