### ISSUE TITLE
Add or Update existing GitHub Action to check for bad links

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#357]
There have been a few pull requests over the years that have identified bad links in our docs. I think it's time for us to have a workflow action that will check for any bad links so we catch them sooner.

The related PR should:
* Check for any bad links in any markdown files (the root docs directory as well as the .docs/ folder for exercises)
* Check for English (US) spelling errors

**Comment by lakshya8066** [comment]
Hey @Stargator can I work on this?

**Comment by Stargator** [comment]
@lakshya8066 Yes, feel free
