### ISSUE TITLE
Does ABOUT.md Need a Mention of Flutter?

### ISSUE THREAD

**Issue by andrewfgarrison** [exercism/dart#366]
Currently in the `ABOUT.md` file for Dart, there is a mention of Angular.dart, but not of Flutter. While the use of Dart for web development is still common, I wonder if updating this part of the file to either include Flutter or to replace Angular with Flutter wouldn't be appropriate.

(My personal opinion is that while Angular.dart is still in use, its focus as a library has largely been eclipsed by Flutter)

**Comment by Stargator** [comment]
@andrewfgarrison I don't think we can make opinions on this. But adding a blurb about Dart's connection to Flutter and how it can be used for multi-platform development would be fine.

**Comment by andrewfgarrison** [comment]
That's fine, I'll add a sentence or two about Flutter to the file and make a pull request.

**Comment by Stargator** [comment]
@andrewfgarrison I'm sorry I got this issue and your PR about the config.json confused as the same thing. Otherwise I should have checked ABOUT.md when this was made. Thanks for checking it though!
