### ISSUE TITLE
Repository name does not match (many) other language repositories

### ISSUE THREAD

**Issue by kotp** [exercism/dart#4]
This one is named "dartlang" rather than "dart" similar to other repositories such as "c" or "go", rather than "golang" or "rubylang".

**Comment by kytrinyx** [comment]
I used the same pattern as dlang where I used the website name for the track ID: https://dlang.org/

https://www.dartlang.org/ and the language name for the language ("Dart").

**Comment by SuperPaintman** [comment]
But you didn't use it for "Elm" - <http://elm-lang.org/>

**Comment by kytrinyx** [comment]
Nope, and I didn't use it for Go which is golang.org

It might be worth starting a discussion about how consistent we need/want to be (over in https://github.com/exercism/discussions/issues)
