### ISSUE TITLE
Hamming exercise needs to be updated due to changes in specification

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#40]
The specification for the Hamming exercise can be [found here](https://github.com/exercism/problem-specifications/tree/master/exercises/hamming).

There are a few exercises that were either added or changed.

The changes should occur in these files:
* exercises/hamming/test/hamming_test.dart
  * This file will reflect the content of canonical-data.json
* exercises/hamming/lib/example.dart
  * This file will have to be updated in case the changes in hamming_test.dart render the solution outdated with the new/changed tests.

To run the tests, execute `pub run test` from the root directory of exercism/dart

**Comment by jerold** [comment]
Hi @Stargator would you be able to clarify what has changed about the Hamming spec?

**Comment by Stargator** [comment]
@jerold No problem.

[In the canonical json](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json), some tests were not implemented. Feel free to keep the current tests and just merge in these other tests.

And ignore any that may seem duplicates of the current batch of tests.

The first case (empty strands) from the json is not implemented.

And the following cases:
* non-unique character in first strand
* non-unique character in second strand
* same nucleotides in different positions
* disallow first strand longer
* disallow second strand longer

**Comment by jerold** [comment]
Thanks @Stargator I've pushed the revert and test changes.

**Comment by Stargator** [comment]
Related Pull Request #48 was merged
