### ISSUE TITLE
How to best run tests locally on just the exercise being worked on?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#411]
I'm working on updating existing exercises per the canonical data in the `problem-specifications` repository.

The README says to execute `dart test` in order to run the tests for all the exercises. Doing this takes a very long time, even if there are no outdated dependencies.

- Is there a way to skip the dependency check?
- Is there a way to run the tests for a single exercise? Right now if I call the command with the path to the exercise, it fails because it is running against the stub rather than the example solution.

**Comment by HornMichaelS** [comment]
Looks like it's possible to set the environment variable `EXERCISE` to specify which exercise to test.

So to run only the tests for pig-latin:

```
EXERCISE=pig-latin dart test
```

**Comment by kytrinyx** [comment]
@HornMichaelS Thank you so much. Where did you find that?

**Comment by HornMichaelS** [comment]
Just looking at the code for [test/exercises_test.dart](https://github.com/exercism/dart/blob/main/test/exercises_test.dart) - I don't think it's documented.

**Comment by kytrinyx** [comment]
Oh, that's totally not where I was looking for test scripts. In languages I've worked in the scripts would be in `bin/` and the library tests would be in `test`. Thanks! I'll open a PR to document it.

**Comment by Stargator** [comment]
The exercises_tests is kind of a script, but it's really a test suite to run all the tests of any practice or curriculum exercise.
