### ISSUE TITLE
Question about initialization in test suites

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#417]
I noticed that sometimes initialization happens within `main()` and sometimes outside of `main()`, and sometimes a mix of both.

E.g.:
**Inside:**
https://github.com/exercism/dart/blob/2d1a3121760cae6674d52e951bf2035726ccd5de/exercises/practice/secret-handshake/test/secret_handshake_test.dart#L3-L6

https://github.com/exercism/dart/blob/2d1a3121760cae6674d52e951bf2035726ccd5de/exercises/practice/collatz-conjecture/test/collatz_conjecture_test.dart#L8-L14

**Outside:**
https://github.com/exercism/dart/blob/2d1a3121760cae6674d52e951bf2035726ccd5de/exercises/practice/diamond/test/diamond_test.dart#L3-L6

**Mix of both:**
https://github.com/exercism/dart/blob/2d1a3121760cae6674d52e951bf2035726ccd5de/exercises/practice/hamming/test/hamming_test.dart#L4-L14

@Stargator @devkabiir What determines whether something should be defined outside of `main` or within it?

**Comment by Stargator** [comment]
As far as code style, that has not been a hard and fast rule. The language obviously supports both.

The only reason I have a wariness of setting a code style is that there's not a lot of ways to enforce it via the tools.

It would have to be either very well documented or we leave it as it stands.

Though, since we are talking specifically about the test suites I'm fine with making a rule about the initialization.

I see the benefits of both ways of doing it. Outside of the main, means that all the initialization happens first and then the main is executed with the groups or tests.

And inside the main, means that we just keep all of our logic within that one function. Which just makes it simpler.

But I have no strong preferences one way or the other.

**Comment by kytrinyx** [comment]
That's useful, thank you. I don't think we need to enforce a standard, but it would definitely be useful if I can just pick one and stick with it when I generate test suites.

If neither is a bad practice or best practice, maybe it doesn't matter which I pick?

**Comment by kytrinyx** [comment]
Excellent, thank you.

**Comment by Stargator** [comment]
@kytrinyx As I am going through the test suites, I realize there is a reason for initializing in the main and out of it.

Initialization out of main allows for the instance (ex: phoneNumber) to be reachable by the tests if main only contains groups.

```dart
final phoneNumber = PhoneNumber();

void main() {
  group('PhoneNumber: Cleanup special characters - ', cleanUpTest);
  group('PhoneNumber: Number length - ', numberLengthTest);
  group('PhoneNumber: Accept only numbers - ', numbersOnlyTest);
  group('PhoneNumber: Area/Exchange Code - ', areaCodeTests);
  group('PhoneNumber: Edge cases - ', exchangeCodeTests);
}

void cleanUpTest() {
  test('cleans the number', () {
    final result = phoneNumber.clean('(223) 456-7890');
    expect(result, equals('2234567890'));
  }, skip: false);
...
```

This can easily be resolved by leaving initialization in main, but then having all the tests still in main regardless of groups.

```dart
final phoneNumber = PhoneNumber();

void main() {
  group('PhoneNumber: Cleanup special characters - ', () {
    test('cleans the number', () {
      final result = phoneNumber.clean('(223) 456-7890');
      expect(result, equals('2234567890'));
    }, skip: false);
  );
  group('PhoneNumber: Number length - ', numberLengthTest);
  group('PhoneNumber: Accept only numbers - ', numbersOnlyTest);
  group('PhoneNumber: Area/Exchange Code - ', areaCodeTests);
  group('PhoneNumber: Edge cases - ', exchangeCodeTests);
}
...
```

**Comment by kytrinyx** [comment]
Last night I realized that that must be the case.
I ended up settling on putting initialization outside main if there are groups and inside main if there are not.
