### ISSUE TITLE
Need More Exercises implemented for Core Path

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#42]
See #38 for what a PR that adds a new exercise covers.

General Overview:
* Choose a problem from [problem specifications repo](https://github.com/exercism/problem-specifications)
 * See [this list](http://exercism.io/languages/dart/todo) sorted by exercises implemented by most other Exercism tracks
  * Recommend looking for a problem that would fit for someone new to the language and complements the other existing problems (ie: tackles different topics)
* Create a directory in exercises/ for the new exercise
* Update the config.json by including the new problem, outlining the topics it covers, labeling it as "core", assigning an initial difficulty score (See [this discussion](https://github.com/exercism/dart/issues/37) for how the current scores were considered, and place it after the last exercise.
* To run the tests, execute `pub run test` from the root directory of exercism/dart

**Comment by kabiir** [comment]
@Stargator I am actively learning dart and would like to contribute multiple exercises, i can implement a lot of the exercises. Should i start by creating new issues for the "core" exercises that are yet to be implemented?

**Comment by Stargator** [comment]
@kabiir There are no  universal "core" exercises except for those the maintainers say are. And except for hello-world, that's pretty universal :)

Feel free to start implementing some exercises and include them in an order you think is right and we can discuss it in the PR in more depth.

**Comment by Stargator** [comment]
Considering we got 10 exercises, I think we have the core finished. Closing.
