### ISSUE TITLE
Why is skip true for all the tests?

### ISSUE THREAD

**Issue by jfacoustic** [exercism/dart#464]
Noticed if you run dart test, it only runs the first test.  Why is skip true for all but the first test?

```dart
    test('year divisible by 2, not divisible by 4 in common year', () {
      final result = leap.leapYear(1970);
      expect(result, equals(false));
    }, skip: true)
```

**Comment by Stargator** [comment]
We implement the test suites to enable refactoring via Text Driven Development. Users don't have to follow that path.

So by only enabling the first test, users can test, implement, and refactor one test at a time until they develop a working solution.

**Comment by jfacoustic** [comment]
Thanks!  That makes sense.
