### ISSUE TITLE
Wide right section cause layout issues

### ISSUE THREAD

**Issue by im-victor-mendez** [exercism/dart#498]
This issue is global, but discovered into dart track
![image](https://github.com/exercism/dart/assets/106124660/856badec-755c-42a7-a572-0a784e23497c)
![image](https://github.com/exercism/dart/assets/106124660/c519e5b8-3a1f-4cd5-a5e6-e3de2715895a)

**Comment by Stargator** [comment]
@ErikSchierboom, this seems like an issue with the styling applied for each Track page. This repo does not apply styling. So this issue belongs to another repo.
