### ISSUE TITLE
I noticed all the testcases except first one are marked for skip. Any reasons ?

### ISSUE THREAD

**Issue by VigneshkumarG** [exercism/dart#511]
<img width="721" alt="Screenshot 2023-11-28 at 9 53 48 PM" src="https://github.com/exercism/dart/assets/38705750/1a1fc80d-03ef-4826-a85e-1049c9726dd8">

When I try to execute the testcases, it is showing that "Test Ignored".

After marking `skip: false`, it runs fine.

Please someone clarify

**Comment by Stargator** [comment]
@VigneshkumarG, to answer your question in the [README](https://github.com/exercism/dart?tab=readme-ov-file#exercise-tests) we explain that by default we try to steer students to a test drive development approach.

So you can approach the exercises anyway you want, but the intent is to allow students to resolve the first test and then unblock the next test, then try to resolve that and so on.
