### ISSUE TITLE
Create scripts to to reduce commands used to validate Pull Requests

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#61]
[Stemming from this comment](https://github.com/exercism/dart/pull/58#discussion_r144105347), the following commands can be run from a script:
1. `pub run test` - All the tests for Dart exercises can be run from the top level of the repo with this command
1. `bin/configlet lint .` - Checks the config.json for formatting issues
1. `bin/configlet fmt .` - Formats the config.json
1. `bin/check_formatting` - Checks All the Dart files for formatting issues
1. `pub run dart_style:format -l 120 -w .` - Formats all the Dart files

I recommend 2 and 4 can be in a script that just checks formatting of the project files.

Then 1, 3, and 5 can be put in a script that validates tests and automatically formats configlet and dart files.

Then there are two files that need to be updated with the new scripts:
* .travis.yml
* README.me

The scripts should be able to be run in Mac, Linux, and Windows with as little duplication as possible. Since we are using Dart, the scripts _could_ written in Dart, but it's up to the author.

**Comment by kabiir** [comment]
Some ideas for the script :

- By default it'll run all 5 task for all exercises.
- There should be an option to perform those tasks for a specific exercise.
- It should have option to perform specific tasks for specific exercise. (maybe not, need opinions) 
- It's name should be sensible (e.g. validate-exercise) along with its args (--all, --nameOfExercise, etc) 
- Possibly hook the script to git-hooks (pre-push) a non-zero exit code will abort the push. 
- Should return zero exit code after successful completion, this will also be helpful in travis-ci
- more ideas here...

**Comment by kabiir** [comment]
Few more ideas
- If canonical-data has tests, there should exists a `exercise_name_test.dart` file in `test` directory.
- Number of tests implemented `>=` Number of tests in canonical-data (It's fine if there are more).
- Each test implemented has flag `skip:true` except the first one.
- The actual `example.dart` should **not** be imported in the exercise_name_test.dart (common mistake).
- The `exercise_name.dart` should be imported in `exercise_name_test.dart`.
- If there exists a description.md in the problem-specification, there should be a readme.md (In case the contributor didn't use our create-exercise tool. )

**Comment by Stargator** [comment]
> There should be an option to perform those tasks for a specific exercise.
That's possible for the scripts that check dart formatting, but the configlet commands check the entire repo's configuration and contents.

> It should have option to perform specific tasks for specific exercise. (maybe not, need opinions)
Currently, it would be checking the format and then formatting the exercise. Just two tasks.

> Possibly hook the script to git-hooks (pre-push) a non-zero exit code will abort the push
If whoever implements it can do that and have it affect anyone that clones the repo, sure.

> Number of tests implemented >= Number of tests in canonical-data (It's fine if there are more).
It would require that for *every* person that clones our repo and make a change, they would need to clone exercism/problem-specifications in order to run this script. I do *not* recommend that path.

> If canonical-data has tests, there should exists a exercise_name_test.dart file in test directory.
We don't need canonical-data to have tests to know there needs to be a dart test file.

In my opinion, this suggestion and the one about validating number of tests. That can be handled during the PR.

**Comment by raphalvessa** [comment]
I'm happy to take this one. I suggest the script(s) be written in Dart so that users can run it on any platform.

**Comment by kabiir** [comment]
@raphalvessa If you can work on this, checkout the points I've written for a start. And create a PR once you're done we'll continue our discussion there for any modifications or more ideas.

**Comment by raphalvessa** [comment]
@kabiir Will do. I'll get started once I have some free time. 🙂

**Comment by raphalvessa** [comment]
I believe this issue has been addressed with PR #70, and can now be closed.

**Comment by Stargator** [comment]
@raphalvessa Thanks for double checking. I missed this.
