### ISSUE TITLE
Update create-exercise to create README.md if description.md exists

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#62]
If the specification in exercism/problem-specifications has a description.md, that can be used to make a README for the generated exercise.

Additionally, from the metadata.yml file, we can take the values for source and source_url and add them to the end of the README.md file.

The easiest way would be to [use the configlet tool within create-exercise to generate the README](https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md#generation) if the problem-specification repo was referenced

**Comment by Stargator** [comment]
@fwip Do you want to take a look at this?

**Comment by Stargator** [comment]
I would also include an update so that if the exercise already exists, there's a newline after the "already exists" message.

**Comment by fwip** [comment]
Sure, I'll take this on.
