### ISSUE TITLE
Make travis-ci tests faster by only testing changed files.

### ISSUE THREAD

**Issue by devkabiir** [exercism/dart#63]
The following git command prints names of changed files in the latest commit.

`git diff --name-only HEAD~1`

Latest commit corresponds to the latest commit of the PR. 
This command outputs the list of files to the `stdin`
This works even for squashed merges.
Here are my proposed changes:
- Check if any `*.dart` files have been changed
    - Run `pub get`,  `pub run test` & `pub run dart_style:format -l 120 -n .` only for that exercise.
- If there are no `*.dart` files changed (could be `*.md` or `*.json`) 
    - perform `configlet lint .` if `*.json` file has been changed (only for that exercise directory)
    - do nothing and return if  `*.md` file have been changed.

I'll start working on this as soon as I get some time, until then if anyone is interested in this, create an empty PR and grab this issue.

**Comment by kabiir** [comment]
Possibly add the same improvement to all other tracks if they don't have it. @kytrinyx This will improve travis-ci builds/tests by a lot. I'd like to know your opinion on this.

**Comment by kytrinyx** [comment]
@kabiir this would be fantastic. Would you open an issue in https://github.com/exercism/discussions/issues? That way we can (at the very least) let other maintainers see what you've done here, and (ideally) make a plan for how to get this implemented in more tracks.

**Comment by Stargator** [comment]
[The builds have been between 1-3 minutes](https://travis-ci.org/exercism/dart/pull_requests), that is trivial considering it checks that all tests are covered especially in cases where there may be ill-intended effects on other parts of the track.

If the builds ever get too long, we can revisit this. But it doesn't seem like an issue this track is facing.

Though, [there is an ongoing conversation](https://github.com/exercism/discussions/issues/204) we could also just listen in to the points that come up in that thread.

**Comment by devkabiir** [comment]
Closing in light of #264
